# Generated by Django 3.1.4 on 2020-12-30 12:19

from django.db import migrations, models
import django.db.models.deletion
import wall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_date', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дата добавление')),
                ('status', models.TextField(blank=True, choices=[('end', 'end'), ('continue', 'continue')], null=True, verbose_name='Статус')),
                ('poster', models.ImageField(upload_to=wall.models.book_poster, verbose_name='Главаня картинка')),
            ],
            options={
                'verbose_name': 'Манхва или Манга',
                'verbose_name_plural': 'Манхва или Манга',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название главы')),
                ('url', models.TextField(verbose_name='Ссылка на главу')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.book', verbose_name='Манга или манхва')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=wall.models.page, verbose_name='Страница')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.chapter', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
