# Generated by Django 3.1.4 on 2020-12-30 06:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/def.jpg', null=True, upload_to=user.models.DefineUserPathImages),
        ),
    ]
